{{- if not .Values.mjsAdmin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mjs-admin-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mjs-eks-refarch.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  password: {{ randAlphaNum 32 }}
{{- end }}