apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-%s" (include "mjs-eks-refarch.fullname" .) "matlab-pv" }}
  labels:
    {{- include "mjs-eks-refarch.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: {{ .Values.matlabPath }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key:  {{ .Values.global.nodeLabel.key }}
              operator: In
              values:
                - {{ .Values.global.nodeLabel.workerValue }}