apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mjs.checkpointPVC }}
  labels:
    {{- include "mjs-eks-refarch.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ default "efs-storage" .Values.storage.efsStorageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mjs.logPVC }}
  labels:
    {{- include "mjs-eks-refarch.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ default "efs-storage" .Values.storage.efsStorageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mjs.workerLogPVC }}
  labels:
    {{- include "mjs-eks-refarch.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ default "efs-storage" .Values.storage.efsStorageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mjs.matlabPVC }}
  labels:
    {{- include "mjs-eks-refarch.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual